name: stats-env
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - jupyterlab
  - ipykernel
  - pandas=2.3.0
  - matplotlib=3.10.3
  - scipy=1.15.3
  - statsmodels=0.14.1
  - seaborn=0.13.2
  